<?php

namespace AppBundle\Repository;

/**
 * AcquirementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcquirementTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
