<?php

namespace AppBundle\Repository;

/**
 * AllowanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowanceRepository extends \Doctrine\ORM\EntityRepository
{
}
