<?php

namespace AppBundle\Repository;

/**
 * FamilyPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
