<?php

namespace AppBundle\Repository;

/**
 * FiscalityYearBearingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscalityYearBearingRepository extends \Doctrine\ORM\EntityRepository
{
}
