<?php

namespace AppBundle\Repository;

/**
 * FiscalityAmountBearingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscalityAmountBearingRepository extends \Doctrine\ORM\EntityRepository
{
}
