<?php

namespace AppBundle\Repository;

/**
 * InterestFiscalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestFiscalityRepository extends \Doctrine\ORM\EntityRepository
{
}
