<?php

namespace AppBundle\Repository;

/**
 * LawPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LawPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
