<?php

namespace AppBundle\Repository;

/**
 * LiquidationFiscalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidationFiscalityRepository extends \Doctrine\ORM\EntityRepository
{
}
