<?php

namespace AppBundle\Repository;

/**
 * PhysicalPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
