<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Property;

/**
 * PhysicalPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalPersonRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     *
     * @param Property $property
     * @return array
     */
    public function findByProperty(Property $property)
    {
        $query = $this->createQueryBuilder('a')
        ->select('a')
        ->leftJoin('a.properties', 'c')
        ->addSelect('c');
        
        $query = $query->add('where', $query->expr()->in('c', ':c'))
        ->setParameter('c', $property)
        ->getQuery()
        ->getResult();
        
        return $query;
    }


}
