<?php

namespace AppBundle\Repository;

/**
 * PriorityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
