<?php

namespace AppBundle\Repository;

/**
 * PropertyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
